name: Cleanup Old Workflows

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0' # 每周日 0 点运行一次

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: false
          releases_keep_latest: 5
          delete_workflows: true
          workflows_keep_day: 10
          gh_token: ${{ secrets.GITHUB_TOKEN }}
