name: Cleanup Old Workflows

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0' # 每周日 0 点运行一次

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old workflows
        uses: dev-drprasad/delete-older-releases@v0.2.2
        with:
          retain_days: 30 # 保留 30 天内的 workflows
          github_token: ${{ secrets.GITHUB_TOKEN }}
